on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go test
        run: go test -shuffle=on -coverprofile coverage.out -timeout 5m ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out

  test-with-race:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go race test
        run: go test -race -shuffle=on -timeout 5m ./...
